before:
  hooks:
    - go mod download
    - make assets/dist

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - openbsd
      - freebsd
    goarch:
      - amd64
      - 386
      - arm64
    ldflags:
      - -extldflags "-static" -s -w -X "main.version={{.Version}}" -X "main.commit={{.Commit}}" -X "main.date={{.Date}}"
    hooks:
      pre: packr
      post: packr clean

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
